language: php

sudo: true
php:
  - 7.1
  - 7.2

service:
  - docker
  - mongodb

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.* DEPENDENCIES=beta

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - phpenv config-rm xdebug.ini; echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - pecl install -f mongodb-stable;
  - composer self-update
  - make composer-compat
  - if [ "$DEPENDENCIES" = "beta" ]; then make composer-config-beta; fi;
  - make composer-install

script:
  - make ci
