language: php

sudo: true
php:
  - 8.0
  - 8.1

service:
  - docker
  - mongodb

matrix:
  fast_finish: true
  include:
    - php: 8.0
      env: SYMFONY_VERSION=6.0.*
    - php: 8.1
      env: SYMFONY_VERSION=6.0.*

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - phpenv config-rm xdebug.ini; echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;
  - pecl install -f mongodb-stable;
  - composer self-update
  - make composer-compat
  - if [ "$DEPENDENCIES" = "beta" ]; then make composer-config-beta; fi;
  - make composer-install

script:
  - make ci
